Repository notvalproate/Algo-Game, pull requests merged in 2023-12, with the labels that each got.

#3 completed japanese translations.
  public/assets/languages/ja.json
Labels: enhancement

#7 remove confetti for losing player
  public/dev/js/helpers.js
Labels: waiting for contributor, waiting for changes

#12 [Fix for #10] - Limiting username to accomodate 16 characters and roomkey to accept 8 characters
  views/index.ejs
Labels: waiting for approval, under review
