Repository notvalproate/Algo-Game, pull requests merged in 2024-10, with the labels that each got.

#17 Italian translation
  .env.example
  public/assets/languages/it.json
  public/dev/css/styles.css
  public/dev/css/styles.css.map
  public/dev/js/language.js
  public/dev/scss/partials/_language.scss
  views/index.ejs
  views/play.ejs
Labels: enhancement

#18 Automate Deployment to Oracle Cloud Infrastructure
  .github/workflows/github-actions-oci.yaml
  modules/environment.js
  server.js
Labels: enhancement

#19 [Fix for Issue #8] Avoid Username Clash In Same Lobby
  modules/socketsHandler.js
  public/dev/js/index.js
  public/dev/js/play.js
  public/prod/play.js
  public/prod/styles.js
  server.js
  webpack.config.js
Labels: bug, enhancement

#20 Algo draw feature
  modules/game.js
  modules/socketsHandler.js
  public/assets/languages/en.json
  public/assets/languages/it.json
  public/assets/languages/ja.json
  public/dev/css/styles.css
  public/dev/css/styles.css.map
  public/dev/js/helpers.js
  public/dev/js/play.js
  public/dev/scss/partials/_modal.scss
Labels: bug, enhancement

#21 Added German translations
  public/assets/languages/de.json
Labels: documentation, enhancement, waiting for changes
